### ISSUE TITLE
Missing Release Notes

### ISSUE THREAD

**Issue by robinschneider** [stackitcloud/stackit-sdk-go#178]
Would be great to have a GitHub Release with Release Notes for each tag.

**Comment by hcsa73** [comment]
Hello, thank for your feedback! We have this in our backlog, to have a way of showing changes for different modules (some of which may come from API changes)

**Comment by vicentepinto98** [comment]
Hello @robinschneider,
We have just published a [Release Note](https://github.com/stackitcloud/stackit-sdk-go/releases/tag/release-2023-12-18) for all of our SDK modules.
You can find the individual changelog of each module on the respective folder under `services` . We will continue to update those from now on :smile:

**Comment by robinschneider** [comment]
@vicentepinto98 Thank you for the update. However, this does not fit our use case.
We use renovate a lot and the way the release notes are right now, they have their own tag instead of the "normal" create a release from existing tag workflow.

If the release notes are generated for each tag like `v0.8.0` from yesterday, we can directly see the change notes in our PRs.
