### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by stackit-pipeline** [stackitcloud/stackit-sdk-go#19]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Other Branches

These updates are pending. To force PRs open, click the checkbox below.

 - [ ] Update actions/checkout action to v4

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update module github.com/stackitcloud/stackit-sdk-go/core to v0.1.1](../pull/44)
 - [ ] [Update module k8s.io/apimachinery to v0.28.2](../pull/45)
 - [ ] [Update module github.com/stackitcloud/stackit-sdk-go/services/postgresql to v0.2.0](../pull/46)
 - [ ] [Update module golang.org/x/oauth2 to v0.12.0](../pull/48)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>github-actions</summary>
<blockquote>

<details><summary>.github/workflows/ci.yaml</summary>

 - `actions/checkout v3`
 - `actions/setup-go v4`

</details>

<details><summary>.github/workflows/renovate.yaml</summary>

 - `actions/checkout v3`
 - `renovatebot/github-action v39.0.5`

</details>

</blockquote>
</details>

<details><summary>gomod</summary>
<blockquote>

<details><summary>core/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `golang.org/x/oauth2 v0.11.0`
 - `k8s.io/apimachinery v0.28.1`

</details>

<details><summary>examples/authentication/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/dns v0.1.0`

</details>

<details><summary>examples/configuration/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/dns v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/postgresql v0.1.0`

</details>

<details><summary>examples/dns/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/dns v0.1.0`

</details>

<details><summary>examples/errorhandling/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/dns v0.1.0`

</details>

<details><summary>examples/logme/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/logme v0.2.0`

</details>

<details><summary>examples/mariadb/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/mariadb v0.2.0`

</details>

<details><summary>examples/opensearch/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/opensearch v0.2.0`

</details>

<details><summary>examples/postgresflex/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/services/postgresflex v0.1.0`

</details>

<details><summary>examples/postgresql/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/postgresql v0.1.0`

</details>

<details><summary>examples/rabbitmq/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/rabbitmq v0.2.0`

</details>

<details><summary>examples/redis/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/redis v0.2.0`

</details>

<details><summary>examples/waiter/go.mod</summary>

 - `go 1.18`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`
 - `github.com/stackitcloud/stackit-sdk-go/services/dns v0.1.0`

</details>

<details><summary>services/argus/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/dns/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/logme/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/mariadb/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/opensearch/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/postgresflex/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/postgresql/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/rabbitmq/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/redis/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/resourcemanager/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

<details><summary>services/ske/go.mod</summary>

 - `go 1.18`
 - `github.com/google/go-cmp v0.5.9`
 - `github.com/stackitcloud/stackit-sdk-go/core v0.1.0`

</details>

</blockquote>
</details>

**Comment by hcsa73** [comment]
Renovate test
