### ISSUE TITLE
Avoid using/changing `http.DefaultClient`

### ISSUE THREAD

**Issue by maboehm** [stackitcloud/stackit-sdk-go#236]
When the user of the library does not provide a custom cient,
`http.DefaultClient` is used, and a custom RoundTripper is set in order to
implement authentication / retries,  e.g.

https://github.com/stackitcloud/stackit-sdk-go/blob/868d87ef3eb0ec636ebf19277fc2056349240591/services/serviceaccount/client.go#L74-L83

This can have unintended consequences and should be avoided in my opinion. Now,
every time I (or another package) uses the default client, it behaves
differently than expected.

I'd suggest to instead create a new client: `cfg.HTTPClient = &http.Client{}`.
This change would need to be done for every service.

**Comment by joaopalet** [comment]
Hi,

Thank you for opening the issue! We have created a bug ticket for this and will work on it soon

**Comment by hcsa73** [comment]
Fixed in the most recent released
